image: Visual Studio 2019 Preview
version: '{build}'

configuration: Debug

skip_branch_with_pr: true

branches:
  except:
    - gh-pages

before_build:
  - dotnet restore

build:
  project: Gw2Sharp.sln
