image: Visual Studio 2019 Preview
version: '{build}'

configuration: Debug

environment:
  sonar_login:
    secure: QDHrFOIyHrdnTjASRiMPjakQGHJzBeHDMVHBoqZ42GRwl2XUCWLdWTFIcMjDprMd

skip_branch_with_pr: true

branches:
  except:
    - gh-pages

before_build:
  - dotnet restore
  - dotnet tool install --global dotnet-sonarscanner
  - ps: >-
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq "") {
        if ($env:APPVEYOR_REPO_TAG -eq "true") {
          dotnet sonarscanner begin /k:"Archomeda_Gw2Sharp" /o:"archomeda-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_login" /d:sonar.branch.name:"$env:APPVEYOR_REPO_BRANCH" /v:"$env:APPVEYOR_REPO_TAG_NAME"
        } else {
          dotnet sonarscanner begin /k:"Archomeda_Gw2Sharp" /o:"archomeda-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_login" /d:sonar.branch.name:"$env:APPVEYOR_REPO_BRANCH"
        }
      } else {
        dotnet sonarscanner begin /k:"Archomeda_Gw2Sharp" /o:"archomeda-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_login" /d:sonar.pullrequest.key:"$env:APPVEYOR_PULL_REQUEST_NUMBER" /d:sonar.pullrequest.branch:"$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH" /d:sonar.pullrequest.base:"$env:APPVEYOR_REPO_BRANCH"
      }

build:
  project: Gw2Sharp.sln

after_test:
  - dotnet sonarscanner end /d:sonar.login="%sonar_login%"
