image: Visual Studio 2019 Preview
version: '{build}'

configuration: Debug

skip_branch_with_pr: true

branches:
  except:
    - gh-pages

before_build:
  - dotnet restore
  - ps: >-
      $version = Get-Content Gw2Sharp/Gw2Sharp.csproj | Select-String -Pattern '<Version>([^<]*)</Version>' -AllMatches | % { $_.Matches.Groups[1].Value }

      (Get-Content Gw2Sharp/Gw2Sharp.csproj) `
        -replace '<Version>([^<]*)</Version>', "<Version>$version-appveyor.$env:APPVEYOR_BUILD_VERSION</Version>" |
      Out-File Gw2Sharp/Gw2Sharp.csproj

      Update-AppveyorBuild -Version "$version-$env:APPVEYOR_BUILD_VERSION"

build:
  project: Gw2Sharp.sln

test_script:
  - dotnet test --configuration %CONFIGURATION% --no-build

after_test:
  - dotnet pack Gw2Sharp -c %CONFIGURATION% --no-build -o pack
  - ps: Remove-Item pack/*.symbols.nupkg

artifacts:
  - path: pack/*.nupkg
