image: mcr.microsoft.com/dotnet/core/sdk:3.1

variables:
  CONFIGURATION: Release

stages:
  - pre-build
  - build
  - post-build
  - test
  - pack
  - deploy

.task:
  except:
    - gh-pages
    - /^build-number-/

pre-build:versioning:
  extends: .task
  stage: pre-build
  image: docker:stable
  services:
    - docker:dind
  script: docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.0.0-linux /repo /updateassemblyinfo Gw2Sharp/Properties/AssemblyVersionInfo.cs /ensureassemblyinfo
  artifacts:
    paths:
      - Gw2Sharp/Properties/AssemblyVersionInfo.cs
    expire_in: 1 day

build:binaries:
  extends: .task
  stage: build
  dependencies:
    - pre-build:versioning
  script: dotnet build Gw2Sharp -c $CONFIGURATION -o bin
  artifacts:
    paths:
      - bin/
    expire_in: 1 day

build:docs:
  extends: .task
  stage: build
  image: mono
  only:
    - master
    - tags
  before_script:
    - apt update
    - apt install -y git wget unzip
  script:
    - wget -q https://github.com/dotnet/docfx/releases/download/v2.43.3/docfx.zip
    - unzip docfx.zip
    - mono docfx.exe Gw2Sharp.DocFX/docfx.json
    - mv Gw2Sharp.DocFX/_site doc
  artifacts:
    paths:
      - doc/
    expire_in: 1 month

post-build:binaries-with-docs:
  extends: .task
  stage: post-build
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  dependencies:
    - build:binaries
  only:
    - master
    - tags
  before_script:
    - dotnet tool install -g InheritDocTool
    - export PATH="$PATH:/root/.dotnet/tools"
  script:
    - InheritDoc -o
  artifacts:
    paths:
      - bin/
    expire_in: 1 month

test:
  extends: .task
  stage: test
  script: dotnet test -c $CONFIGURATION

pack:
  # TODO: Make this autoversioned
  extends: .task
  stage: pack
  dependencies:
    - post-build:binaries-with-docs
  only:
    - tags
  script:
    - dotnet build Gw2Sharp -c $CONFIGURATION
    - cp bin/Gw2Sharp.xml Gw2Sharp/bin/$CONFIGURATION/netstandard2.0/
    - dotnet pack Gw2Sharp -c $CONFIGURATION --no-build --include-symbols -p:SymbolPackageFormat=snupkg -o pack
  artifacts:
    paths:
      - pack/
    expire_in: 1 month

deploy:docs:
  extends: .task
  stage: deploy
  image: ubuntu
  dependencies:
    - build:docs
  only:
    - master
    - tags
  before_script:
    - apt update
    - apt install -y git
  script:
    - git config --global credential.helper store
    - git config --global user.name $GITLAB_USER_NAME
    - git config --global user.email $GITLAB_USER_EMAIL
    - git clone https://${GITHUB_PAGES_TOKEN}@github.com/Archomeda/Gw2Sharp.git --branch gh-pages repo_doc
    - mkdir -p repo_doc/${CI_COMMIT_REF_NAME}
    - rm -rf repo_doc/${CI_COMMIT_REF_NAME}/*
    - cp -rf doc/* repo_doc/${CI_COMMIT_REF_NAME}
    - cd repo_doc
    - git add -A
    - |
      if [[ `git status --porcelain` ]]; then
        git commit -m "Update documentation for ${CI_COMMIT_REF_NAME} (${CI_COMMIT_SHORT_SHA})"
        git push origin gh-pages
      fi

deploy:github:
  extends: .task
  stage: deploy
  image: ubuntu
  dependencies:
    - post-build:binaries-with-docs
    - pack
  only:
    - tags
  before_script:
    - apt update
    - apt install -y tar wget zip
  script:
    - wget -q https://github.com/tcnksm/ghr/releases/download/v0.12.1/ghr_v0.12.1_linux_amd64.tar.gz
    - tar -zxf ghr_v0.12.1_linux_amd64.tar.gz
    - mv ghr_v0.12.1_linux_amd64/ghr ./
    - mkdir artifacts
    - zip -r artifacts/Gw2Sharp.zip bin/*
    - cp pack/* artifacts/
    - ./ghr -t ${GITHUB_RELEASE_TOKEN} -u Archomeda -r Gw2Sharp -n ${CI_COMMIT_REF_NAME} -draft ${CI_COMMIT_REF_NAME} artifacts

deploy:nuget:
  extends: .task
  stage: deploy
  dependencies:
    - pack
  only:
    - tags
  script:
    - dotnet nuget push pack/Gw2Sharp.*.nupkg -s https://api.nuget.org/v3/index.json -k ${NUGET_RELEASE_TOKEN}
