path_classifiers:
  test:
    - Gw2Sharp.Tests

queries:
  - include: "*"
  - exclude:
      tags:
        - cs/catch-of-all-exceptions
        - cs/missed-using-statement
        - cs/similar-file
        - cs/useless-gethashcode-call

extraction:
  csharp:
    index:
      dotnet:
        version: 3.0.100-preview6-012264
