name: CI

on: [push]

jobs:
  test:
    name: Test with dotnet ${{ matrix.dotnet }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet:
          - 2.2.108
          - 3.0.100-preview7-012821
          - 3.0.100-preview8-013656
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build
        run: dotnet build Gw2Sharp -c Release
      - name: Test
        run: dotnet test -c Release
