name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        name: Install .NET Core 3.1
        with:
          dotnet-version: "3.1.102"
      - name: Run dotnet build
        run: dotnet build Gw2Sharp -c Release
      - name: Run dotnet test
        run: dotnet test -c Release

  nightly:
    name: Nightly
    runs-on: windows-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        name: Install .NET Core 3.1
        with:
          dotnet-version: "3.1.102"
      - name: Install InheritDocTool
        shell: powershell
        run: dotnet tool install --global InheritDocTool
      - name: Patch nightly version
        shell: powershell
        run: |
          $version = GitVersion /output json /updateassemblyinfo Gw2Sharp/Properties/AssemblyVersionInfo.cs /ensureassemblyinfo
          Write-Output $version
          $version = $version | ConvertFrom-Json

          $nuget = $version.SemVer
          if ($version.BranchName -eq "master") {
            $nuget += "-master.$($version.CommitsSinceVersionSource)"
          }
          Write-Output "Assembly version: $($version.AssemblySemVer)"
          Write-Output "Assembly file version: $($version.AssemblySemFileVer)"
          Write-Output "Informational version: $($version.InformationalVersion)"
          Write-Output "NuGet version: $nuget"
          echo "::set-env name=VERSION::$nuget"
      - name: Run dotnet build
        run: dotnet build -c Release -p:VERSIONED_BUILD=$env:VERSION
      - name: Run InheritDocTool
        shell: powershell
        run: InheritDoc -o
      - name: Run dotnet pack
        run: dotnet pack Gw2Sharp -c Release --no-build -p:VERSIONED_BUILD=$env:VERSION
      - name: Run dotnet nuget push
        run: dotnet nuget push **/*.symbols.nupkg -s "https://www.myget.org/F/gw2sharp/api/v2/package" -k "${{ secrets.MYGET_TOKEN }}"
