name: CI

on:
  push:
    tags-ignore:
      - v*

jobs:
  # Unit tests
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        dotnet:
          - "3.1.102"
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        name: Install .NET Core ${{ matrix.dotnet }}
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Run dotnet build
        run: dotnet build Gw2Sharp -c Release
      - name: Run dotnet test
        run: dotnet test -c Release

  # Nightly packaged build
  nightly:
    name: Nightly build
    runs-on: windows-latest
    needs: [test]
    strategy:
      fail-fast: false
      matrix:
        dotnet:
          - "3.1.102"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        name: Install .NET Core ${{ matrix.dotnet }}
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Patch nightly version
        shell: powershell
        run: |
          $version = GitVersion /output json /updateassemblyinfo Gw2Sharp/Properties/AssemblyVersionInfo.cs /ensureassemblyinfo | ConvertFrom-Json
          $nuget = $version.SemVer
          if ($version.BranchName -eq "master") {
            $nuget += "-master.$($version.CommitsSinceVersionSource)"
          }
          Write-Output "Assembly version: $($version.AssemblySemVer)"
          Write-Output "Assembly file version: $($version.AssemblySemFileVer)"
          Write-Output "Informational version: $($version.InformationalVersion)"
          Write-Output "NuGet version: $nuget"
          echo "::set-env name=VERSION::$nuget"
      - name: Run dotnet build
        run: dotnet build -c Debug -p:VERSIONED_BUILD=${{ VERSION }}
      - name: Run dotnet pack
        run: dotnet pack Gw2Sharp -c Debug --no-build -p:VERSIONED_BUILD=${{ VERSION }}
      - name: Run dotnet nuget push
        run: dotnet nuget push **/*.symbols.nupkg -s "https://www.myget.org/F/gw2sharp/api/v2/package" -k "${{ secrets.MYGET_TOKEN }}"
