name: 'Command: Test'

on:
  repository_dispatch:
    types: [test-command]

jobs:
  pre:
    name: Pre-Run
    runs-on: ubuntu-latest
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          edit-mode: replace
          body: |
            🚀 Test run has started.
            👉 [Check the output here.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: [pre]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-2022
        dotnet:
          - net6.0
          - net5.0
          - netcoreapp3.1
          - net461
        exclude:
          - os: ubuntu-latest
            dotnet: net461
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.client_payload.pull_request.number }}/merge
      - name: Run dotnet test
        run: dotnet test -c Release -f ${{ matrix.dotnet }}

  sonarcloud:
    name: Analysis
    runs-on: windows-2022
    needs: [pre]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.client_payload.pull_request.number }}/merge
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '>=11'
      - uses: Archomeda/sonarcloud-dotnet-action@v1
        with:
          ref: refs/pull/${{ github.event.client_payload.pull_request.number }}/merge
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          sonarOrganization: archomeda-github
          sonarProject: Archomeda_Gw2Sharp
          sonarAdditionalArgs: /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml /d:sonar.scm.revision=${{ github.event.client_payload.pull_request.head.sha }}
      - name: Run dotnet test
        run: dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

  post-successful:
    name: Post-Run successful
    runs-on: ubuntu-latest
    needs: [test, sonarcloud]
    if: success()
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          edit-mode: replace
          body: |
            ✔ Test run was successful.
            👉 [Check the output here.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          reactions: hooray

  post-failed:
    name: Post-Run failed
    runs-on: ubuntu-latest
    needs: [test, sonarcloud]
    if: failure()
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          edit-mode: replace
          body: |
            ❌ Test run has failed.
            👉 [Check the output here.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          reactions: hooray
