name: Command dispatch

on:
  issue_comment:
    types: [created]

jobs:
  commandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commands: test, cleanup
          issue-type: pull-request
