name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  # Build docs
  build:
    name: Build docs
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download docfx
        shell: powershell
        run: |
          Invoke-WebRequest https://github.com/dotnet/docfx/releases/download/v2.43.3/docfx.zip -OutFile docfx.zip
          7z e docfx.zip
      - name: Generate docs
        run: ./docfx.exe Gw2Sharp.DocFX/docfx.json
      - name: Zip docs
        run: 7z a docs.zip Gw2Sharp.DocFX/_site/*
      - name: Upload docs
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs.zip

  # Push docs
  push:
    name: Push docs
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download docs
        uses: actions/download-artifact@v1
        with:
          name: docs
      - name: Replace docs
        run: |
          rm -rf ${GITHUB_REF##*/}
          7z e docs/docs.zip -o${GITHUB_REF##*/}
          rm -rf docs

          git add -A
          if [[ `git status --porcelain` ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "Github Action"
            git commit -m "Update documentation for ${GITHUB_REF##*/} (${GITHUB_SHA:0:7})"
          fi
      - name: Push docs
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
