name: PR

on: [pull_request]

jobs:
  # Unit tests
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet:
          - "3.1.102"
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        name: Install .NET Core ${{ matrix.dotnet }}
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Run dotnet build
        run: dotnet build Gw2Sharp -c Release
      - name: Run dotnet test
        run: dotnet test -c Release
