name: Publish version

on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    runs-on: windows-2022
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        if: matrix.dotnet_version != ''
        with:
          dotnet-version: ${{ matrix.dotnet_version }}
      - name: Generate version
        id: version
        shell: powershell
        run: |
          $version = $env:GITHUB_REF_NAME -match "^v(\d+\.\d+\.\d+(-[\w\d]+(\.[\w\d]+)*)?)$"
          echo "Version derived from tag: $version"
          echo "value=$version" >> $GITHUB_OUTPUT
      - name: Install InheritDocTool
        shell: powershell
        run: dotnet tool install --global InheritDocTool
      - name: Run dotnet build
        run: dotnet build -c Release -p:Version=${{ steps.version.outputs.value }}
      - name: Run InheritDocTool
        shell: powershell
        run: InheritDoc -o
      - name: Zip binaries
        shell: powershell
        run: 7z a Gw2Sharp.zip ./Gw2Sharp/bin/Release/*
      - name: Run dotnet pack
        run: dotnet pack Gw2Sharp -c Release --no-build --include-symbols -p:SymbolPackageFormat=snupkg -p:Version=${{ steps.version.outputs.value }} -o pack
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            Gw2Sharp.zip
            pack/*
