name: Publish version

on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    runs-on: windows-2022
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
      - name: Generate version
        id: version
        shell: pwsh
        run: |
          $env:GITHUB_REF_NAME -match "^v((\d+\.\d+\.\d+)(-([\w\d]+(\.[\w\d]+)*))?)$"
          $version = $matches[2]
          $suffix = $matches[4]
          echo "Version: '$version' - Suffix: '$suffix'"
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "suffix=$suffix" >> $env:GITHUB_OUTPUT
      - name: Run dotnet build
        run: dotnet build -c Release -p:VersionPrefix=${{ steps.version.outputs.version }} -p:VersionSuffix=${{ steps.version.outputs.suffix }}
      - name: Zip binaries
        shell: pwsh
        run: 7z a Gw2Sharp.zip ./Gw2Sharp/bin/Release/*
      - name: Run dotnet pack
        run: dotnet pack Gw2Sharp -c Release --no-build --include-symbols -p:SymbolPackageFormat=snupkg -p:VersionPrefix=${{ steps.version.outputs.version }} -p:VersionSuffix=${{ steps.version.outputs.suffix }} -o pack
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            Gw2Sharp.zip
            pack/*
