name: SonarCloud

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  sonarcloud:
    name: Analysis
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '>=11'
      - uses: Archomeda/sonarcloud-dotnet-action@v1
        with:
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          sonarOrganization: archomeda-github
          sonarProject: Archomeda_Gw2Sharp
          sonarAdditionalArgs: /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
      - name: Run dotnet test
        run: dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
